### ISSUE TITLE
ARMv6 is not ARMhf

### ISSUE THREAD

**Issue by Rumpick** [linuxserver/docker-ombi#48]
The README states that a supported architecture is armhf, but the tag is `arm32v6-latest`. As Arm32v6 is armel, this information is conflicting.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

OS: HypriotOS
``` docker create   --name=ombi-core   -e PUID=1000   -e PGID=1000   -e TZ=America/Vancouver   -p 3579:3579   -v /home/pirate/docker/ombi-test:/config   --restart unless-stopped   linuxserver/ombi:arm32v6-latest```
Log:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 267.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 267.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

This has been mentioned on a different issue, https://github.com/linuxserver/docker-resilio-sync/issues/20 and I believe the tag should be updated to clarify the actual supported architecture.

**Comment by thelamer** [comment]
Yeah we know, but in dockerhub manifest we tag it arm without a v7 or v6 flag as we actually do have v6 images with Alpine 3.8 that up until about two days ago (many rebased to alpine 3.9 which moved to armv7)  made up the majority of our library. 

Since the build logic is universal across all repos we will likely just template this in when we have migrated the last of the v6 images over and no longer offer armel.

**Comment by thelamer** [comment]
Closing as we do have plans for this , it is just not specific to any one repo. The Alpine 3.9 migration completion will likely be the trigger to make this change.
