### ISSUE TITLE
[Feature] Optionally support MySQL/MariaDB 

### ISSUE THREAD

**Issue by rickatnight11** [linuxserver/docker-ombi#63]
##  Feature Request

Ombi added optional support for MySQL/MariaDB (https://github.com/tidusjar/Ombi/pull/3241) in November '19.  It'd be really useful if this image supported this feature in two ways:

1. Operator manages the database separately and simply provides the host/port/creds.
2. Leverage the official MySQL (https://hub.docker.com/_/mysql) or MariaDB (https://hub.docker.com/_/mariadb) images automatically

Instructions for configuring Ombi to use a different database than the default local SQLite DB:

https://github.com/tidusjar/Ombi/wiki/Using-a-different-database

**Comment by aptalca** [comment]
It should already work. Just drop your `database.json` file into /config and restart

**Comment by rickatnight11** [comment]
Mmm, that's a good point.  I suppose, then, the request is more for #2, then, for operators that don't want to manage or think about the database, but do want the performance/stability benefits of a standalone database.

**Comment by aptalca** [comment]
I don't follow. What exactly do you expect us to automate? Feel free to set up and use any external database you like. That has nothing to do with this image.

All you need to do here is put your database info into a `database.json` file and drop it into the config folder. I suspect at some point the `database.json` file will be integrated into ombi's gui settings so you can enter the external database info into the gui rather than a manual file.

**Comment by rickatnight11** [comment]
Yeah, you're right.  This repo is for a single image.  Anything someone wants to do here would involve multiple images and something like `docker-compose`.

**Comment by aptalca** [comment]
@rickatnight11 for some of our images that require mysql, we include compose instructions for reference. See here for an example: https://github.com/linuxserver/docker-codimd#docker-compose
